# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BPT_TableView' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'RoundedViews', '~> 1.0'

  # Pods for BPT_TableView

end
